import Link from 'next/link';
import Image from 'next/image';
import { browseAuctions } from '@/lib/server/marketplace';
import { AuctionCard } from '@/components/auction-card';
import { Countdown } from '@/components/countdown';
import { ArrowUpRight, ArrowRight, ShieldCheck, Gavel, Eye } from '@/components/icons';
import { formatIDR } from '@/lib/auction';
export default async function Home(){
  let auctions: Awaited<ReturnType<typeof browseAuctions>> = [];
  let catalogueUnavailable = false;
  try { auctions = await browseAuctions(); } catch { catalogueUnavailable = true; }
  const live=auctions.filter(a=>a.status==='LIVE');const featured=live.find(a=>a.featured)??live[0];const sold=auctions.filter(a=>['COMPLETED','PAID','FULFILLMENT'].includes(a.status));const ending=[...live].sort((a,b)=>a.endsAt.localeCompare(b.endsAt)).slice(0,3);return <>
{catalogueUnavailable && <div className="page"><p className="error-banner" role="alert">The catalogue is temporarily unavailable. Please try again shortly.</p></div>}
<section className="hero"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="little-line"/>THE EXTRAORDINARY, WITHIN REACH</div><h1>Rare things.<br/><em>Real prices.</em></h1><p>For the curious. The collectors. The ones who know.<br className="desktop-break"/> Discover remarkable objects. Decide what they’re worth.</p><Link className="button hero-cta" href="/auctions">Explore the auctions <ArrowUpRight size={18}/></Link><div className="hero-footnote"><span className="status-dot"/><span>OPEN BIDDING. ENDLESS POSSIBILITY.</span></div></div>{featured&&<div className="hero-feature"><div className="hero-image"><Image src={featured.images[0]||'/images/camera.png'} alt={featured.imageAlt} fill priority sizes="(max-width: 800px) 100vw, 55vw"/><div className="hero-lot"><span>THE COLLECTOR’S EDIT</span><span>LOT 001 / {featured.category.toUpperCase()}</span></div><span className="hero-image-caption">A moment in time. A lifetime of stories.</span><Link href={`/auction/${featured.slug}`} className="hero-image-link" aria-label={`View ${featured.title}`}><ArrowUpRight size={26}/></Link></div><div className="hero-auction-meta"><div><span className="eyebrow">IN THE SPOTLIGHT</span><Link href={`/auction/${featured.slug}`}>{featured.title}</Link><span className="hero-object-subtitle">{featured.condition} · {featured.seller.city}</span></div><div><span className="label">CURRENT BID</span><strong>{formatIDR(featured.currentPrice)}</strong><span>{featured.bidderCount} bidders · {featured.watchCount} watching</span></div><div className="hero-time"><span className="label"><span className="status-dot"/> LIVE AUCTION</span><Countdown endsAt={featured.endsAt} serverTime={featured.serverTime}/></div></div></div>}</section>
<div className="category-strip"><span>FOLLOW YOUR CURIOSITY</span>{[['Watches','watches'],['Cameras','cameras'],['Cards','cards'],['Sneakers','sneakers'],['Design','design'],['Gaming','gaming']].map(([name,slug])=><Link key={slug} href={`/auctions?category=${slug}`}>{name}<ArrowUpRight size={13}/></Link>)}</div>
<section className="section live-section"><div className="section-heading"><div><span className="eyebrow"><span className="status-dot"/> THE FLOOR IS OPEN</span><h2>Worth a closer look.</h2></div><Link className="text-link" href="/auctions">All live auctions <ArrowUpRight size={17}/></Link></div><div className="auction-grid">{live.slice(0,4).map(a=><AuctionCard key={a.id} auction={a}/>)}</div></section>
<section className="ending-section section"><div className="ending-intro"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>Going,<br/><em>going…</em></h2><p>Some opportunities don’t wait.<br/>These auctions are entering their final act.</p><Link className="text-link" href="/auctions?sort=ending-soon">Ending soon <ArrowRight size={18}/></Link></div><div className="ending-list">{ending.map((a,i)=><Link href={`/auction/${a.slug}`} className="ending-row" key={a.id}><span className="ending-number">0{i+1}</span><div className="ending-thumb"><Image src={a.images[0]} alt={a.title} fill sizes="100px"/></div><div className="ending-object"><span className="eyebrow">{a.category}</span><h3>{a.title}</h3><span>{a.bidCount} bids · {a.condition}</span></div><div className="ending-price"><strong>{formatIDR(a.currentPrice)}</strong><Countdown endsAt={a.endsAt} serverTime={a.serverTime} compact/></div><ArrowUpRight size={21}/></Link>)}</div></section>
<section className="manifesto section"><span className="eyebrow">A MARKET BUILT ON KNOWING</span><h2>Good objects have a story.<br/><em>Great markets let it continue.</em></h2><div className="trust-grid"><div><ShieldCheck strokeWidth={1.2}/><h3>People you can trust.</h3><p>Seller verification and considered condition standards. Know who you’re buying from.</p><Link href="/seller-policy">Our seller standards <ArrowUpRight size={14}/></Link></div><div><Gavel strokeWidth={1.2}/><h3>The market decides.</h3><p>Transparent bidding. Private maximums. Fair extensions that give everyone time to respond.</p><Link href="/auction-rules">How auctions work <ArrowUpRight size={14}/></Link></div><div><Eye strokeWidth={1.2}/><h3>Look closer. Bid better.</h3><p>Detailed photography, honest descriptions, and a clear path to raise concerns.</p><Link href="/buyer-protection">Buying with confidence <ArrowUpRight size={14}/></Link></div></div></section>
{sold.length>0&&<section className="section sold-section"><div className="section-heading"><div><span className="eyebrow">THE MARKET HAS SPOKEN</span><h2>Found their next home.</h2></div><Link className="text-link" href="/sold">Explore the price archive <ArrowUpRight size={17}/></Link></div><div className="auction-grid">{sold.slice(0,4).map(a=><AuctionCard key={a.id} auction={a}/>)}</div></section>}
<section className="seller-banner"><div><span className="eyebrow">SOMETHING SPECIAL IN YOUR COLLECTION?</span><h2>Let the right people find it.</h2><p>A considered audience. An open market. Your object’s next chapter.</p></div><Link className="button button-light" href="/sell">Sell with AUCTA <ArrowUpRight size={18}/></Link></section></>}
